[project]
name = "trabajo-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "neo4j>=5.28.1",
    "pydantic-settings>=2.10.1",
    "pydotenv>=0.0.7",
    "pymongo[srv]>=4.13.2",
]
